config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  # get 'home/index'
  resources :posts
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
    validates_presence_of :title, :body, :category
    # attr_accessor :title, :body, :category_id, :author_id
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @title = @category.name
    @post = @category.posts
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
        @posts = Post.all
        # @content_first = "This is some sample text for our awesome new Ruby blog";
        # @content_second = "This is some sample text for our awesome new Ruby blog";
    end
    def show
        @post = Post.find(params[:id])
    end
    def new
        @post = Post.new
        @category = Category.all
    end
    def create
        @post = Post.new(post_params)
       if @post.save
            # render json: @post, status: :created
            redirect_to posts_path, :notice => "your post has been saved"
       else 
        # render json: @post.errors, status: :unprocessable_entity
        render "new"
    end
end
    def edit
        @post = Post.find(params[:id])
        
    end
    def update
        @post = Post.find(params[:id])
        if @post.update(post_params)
            redirect_to posts_path, :notice => "your post has been updated"
        else
            render "edit"
        end
    end
    def destroy
        @post = Post.find(params[:id])
        @post.destroy
        redirect_to posts_path, :notice => "Your post has been deleted"
    end
    
  def post_params
    params.require(:post).permit(:title, :body ,:category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">

<table>
<tbody>
<tr>
<td><%= category.name %></td>

</tr>
</tbody>
</table>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
<br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
<div id="categories">
  <% @categories.each do |category| %>

<li><%= link_to category.name, category %></li>

  <% end %>
  </ul>
</div>
<br>

<!-- <%= link_to "New category", new_category_path %> -->

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<!--
<%= render @category %>

<div>
  <%= link_to "Back to categories", categories_path %>

</div>
-->

<h1><%= @category.name %></h1>
<% if @post.each do |post| %>
<h3><%= link_to post.title,post %></h3>
<p><%= post.body %></p>
<% end.empty? %>
<p>Sorry,there are no posts in this category</p>
<% end %>
<%= link_to "Back to category", categories_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <% if notice %>
    <%= notice %>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Posts</h1>

<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title  %><br />
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body  %><br />
    </p>
    <p>
        <%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]}, {:include_blank => "Select One"} %><br />
    </p>
    <p>
        <%= f.submit "Update Post" %>
    </p>

<% end %>
<%= link_to "go back", post_path %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
<h3><%= link_to post.title,post %></h3>
<p><%= post.body %></p>
<hr>
<% end %>
<%= link_to "add new" , new_post_path %>

app/views/posts/new.html.erb
<h1>Add New Posts</h1>

<%= form_for @post do |f| %>
    <p>
        <%= f.label :title %><br />
        <%= f.text_field :title  %><br />
    </p>
    <p>
        <%= f.label :body %><br />
        <%= f.text_area :body  %><br />
    </p>
    <p>
        <%= f.select :category_id, Category.all.collect {|x| [x.name,x.id]}, {:include_blank => "Select One"} %><br />
    </p>
    <p>
        <%= f.submit "Add Post" %>
    </p>

<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<small><%= @post.created_at.strftime("%b %d. %y")%></small>
<p><%= @post.body %></p>
<p>Category: <%= link_to @post.category.name, category_path(:id => @post.category.id)  %></p>
<p><%= link_to "back",posts_path %></p>
<!-- <%= link_to "Edit Post", edit_post_path%> | <%= button_to "Delete", @post, method: :delete %> -->